#!/usr/bin/env ruby

DEFAULT_TASK_FILE = "tasks.txt"

class Task
  attr_accessor :name, :lines, :desc

  def initialize()
    @name = nil
    @lines = []
    @desc = nil
  end
end

def parse(src)
  name = nil
  desc = nil
  lines = []
  is_first = true
  tasks = []

  task = Task.new

  src.each_line { |line|
    # p line
    if /^([a-zA-Z_].*):/ =~ line
      name = $1
      if is_first
        is_first = false
      else
        tasks << task # 直前のタスクを確定
      end
      task = Task.new
      task.name = name
    else
      if /# desc: (.+)/ =~ line
        task.desc = $1
      else
        task.lines << line
      end
    end
  }
  tasks << task

  tasks
end

def list_tasks(tasks)
  tasks.each{ |t|
    puts "#{t.name}: #{t.desc}"
  }
end

def exec_task(tasks, task_name, args)
  task_setup = tasks.find { |t| t.name == "__setup__"}
  task = tasks.find{ |t| t.name == task_name}

  if task.nil?
    $stderr.puts "no such task: #{task_name}"
    $stderr.puts ""
    $stderr.puts "available tasks:"
    list_tasks(tasks)
    exit 1
  end

  tmp_sh = "./z_tmp.sh"
  File.open(tmp_sh, "wb"){ |f|
    task_setup.lines.each{ |line|
      f.print line
    }
    task.lines.each{ |line|
      f.print line
    }
  }

  # system "cat", tmp_sh
  system "bash", tmp_sh, *args
  exit $?.to_i
end

def print_sample
  puts <<-EOB
# -*- mode: shell-script -*-
# This script was generated by simple_task_launcher.rb

__setup__:
  _print_project_dir() {
    ( cd "$(dirname "$0")"; pwd )
  }

  PROJECT_DIR="$(_print_project_dir)"

  set -o errexit
  set -o nounset

sample:
  # desc: Sample task
  # cd ${PROJECT_DIR}/foo/bar
  echo "Hi"
  EOB
end

def print_help
  puts <<~EOB
    Example:
      {this_command} {task_name}

    Options:
      -l, --list
      --print-sample
      --help
  EOB
end

def read_tasks
  unless File.exist?(DEFAULT_TASK_FILE)
    $stderr.puts <<~MSG
      Task file (#{DEFAULT_TASK_FILE}) not found.
      Run the following command:
        simple_task_launcher.rb --print-sample > tasks.txt
      or
        simple_task_launcher.rb --help
    MSG
    exit 1
  end

  src = File.read(DEFAULT_TASK_FILE)
  parse(src)
end

# --------------------------------

case ARGV[0]
when "-l", "--list"
  tasks = read_tasks()
  list_tasks(tasks)
when "--print-sample"
  print_sample
when "--help"
  print_help
else
  if ARGV.empty?
    $stderr.puts <<~MSG
      Task name is required.
      Run as following:
        simple_task_launcher.rb {task_name}
      or
        simple_task_launcher.rb --help
    MSG
    exit 1
  end

  tasks = read_tasks()
  task_name = ARGV.shift
  exec_task(tasks, task_name, ARGV)
end
